name: commitlint

on:
  push:
    tags-ignore:
      - "v*"
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install correct Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install correct Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run `lint:check` npm script
        run: npm run lint:check

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install correct Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run `format:check` npm script
        run: npm run format:check

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install correct Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run `test:ci` npm script
        run: npm run test:ci
      - if: always()
        name: Upload the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jest-report
          path: ./test-report.html
          retention-days: 14
